name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  validate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install htmlhint and stylelint globally
        run: |
          npm install -g htmlhint stylelint

      - name: Validate HTML with htmlhint
        run: htmlhint **/*.html

      - name: Validate CSS with stylelint
        run: stylelint "**/*.css"
